### ISSUE TITLE
Resources name conflict with ConstraintLayout 2.1.4

### ISSUE THREAD

**Issue by Nojipiz** [mercadolibre/meli-card-drawer-android#116]
The resource name 'corner_radius_card' 
https://github.com/mercadolibre/meli-card-drawer-android/blob/0e1f756e36decc0d03351faabf1c884eb7d86b9e/carddrawer/src/main/res/values/attrs.xml#L17
Creates a conflict with the resource called  'corner_radius_card' in ConstraintLayout library at version 2.1.4, and the apps can't build succesfully.

I think this library can change the name to something more specific. :P

**Comment by guchito9** [comment]
Hi, this library was never fully intended for public use and it's deprecated.

Maybe you can fork or replicate the code in your end to fix it.

**Comment by Nojipiz** [comment]
Isn't that simple, this is a dependecy of https://github.com/mercadopago/px-android, actually the problem happens between px-android and constraintlayout .

**Comment by guchito9** [comment]
Hi, px-android is also deprecated, it isn't receiving real updates for more than two years now. So if you want to use px-android you should stick with the older version of constraint layout
